version: '3'
services:
  fhir_validator_app:
    build:
      context: .
    depends_on:
      - fhir_validator_service
    environment:
      validator_base_path: /validator
    ports:
      - "80:80"
  fhir_validator_service:
    image: infernocommunity/fhir-validator-service:latest
    volumes:
      - ./igs:/home/igs/package
    ports:
      - "4567:4567"
